name: CI/CD
on:
    pull_request:
    push:
        branches:
        - main
        - develop
        - hotfix/*
jobs:
    build:
        name: Build
        runs-on: [self-hosted, linux]
        strategy:
            fail-fast: false
            
        steps:
            - uses: actions/checkout@v3
            - name: Install .NET Core SDK
              uses: actions/setup-dotnet@v3
              with:
                global-json-file: global.json
            - name: Install dependencies
              run: dotnet restore
            - name: Build
              run: dotnet build --configuration Release --no-restore
            - name: Test
              run: dotnet test --no-restore --verbosity normal
